# These are supported funding model platforms

github: # https://startar-bronze.github.io/accueil.html
buy_me_a_coffee: # send a paypal to pro.nzaba@yahoo.fr
thanks_dev: # write to notairebtc@yahoo.fr ,  for GET IBAN
custom: # donate to https://paypal.me/nzabamba
Bitcoin BTC: bc1qdq90qlwrueaq23jxndmg63yfda0m3z52y4j759
ETHERUM ETH: 0xD13674e9342D3DC3b904a56BCf5F28D8Ce1A3474
BNB : 0xD13674e9342D3DC3b904a56BCf5F28D8Ce1A3474
SOLANA: GBtoAyQzgpx3otAALT6VRXzQCWfyMDVdfYpFZc1ALP1i
DOGE: DGfZwjqm4NFQP98Z7KgoQ8oDnZCdYE9Bdd
